Feature/conversations integration
infobip-community/restaurant-reservations-demo pull request #15
Opened 2023-01-30 17:57 UTC by cvaleroib

2023-01-30 19:27 UTC, zaidajef requested changes

2023-01-30 19:27 UTC, zaidajef commented on client/src/pages/home/Home.tsx
> +// @ts-ignore
Why do you need to ignore typescript warnings?

2023-01-30 19:43 UTC, EsaulEF commented on client/src/pages/home/Home.tsx
> +// @ts-ignore
this can be removed

2023-02-02 20:07 UTC, EsaulEF approved these changes

2023-02-02 20:07 UTC, zaidajef approved these changes

2023-02-02 20:08 UTC, merged